name: Sync from template
on:
  # cronjob trigger
  schedule:
    - cron: "0 0 1 * *"
  # manual trigger
  workflow_dispatch:
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      pull-requests: write
      actions: write
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          token: ${{ secrets.PAT_Token }}

      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v1.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_repo_path: alshedivat/al-folio
          upstream_branch: upstream-changes



            
